### ISSUE TITLE
List of cohorts shows two "- ALL individuals -"

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#10]
The list of cohorts shows two "- ALL individuals -", one of which is really out there for this owner name, and is NOT 1, and a second which is generated by the code(?) as 1. The generated one should go, especially now that we have remapping in-place.

**Comment by Viqsi** [comment]
Really, this should be handled by the backend; it's assuming there would only ever be one ALL Individuals and thus returning everything.

**Comment by Viqsi** [comment]
There's been something of an ongoing misunderstanding between myself and @WValenti about the real implications of this issue and how to handle it - mostly in terms of what's being addressed and how. The state it's currently in is that It's pretty much entirely on my end - I need to adapt diverRPC to, whenever it expects a resultSetId, track two: the "visible" resultSetId (assigned specifically to a user) and the "actual" resultSetId (that which the "visible" ID is a pointer to).

Fixing that - and keeping track of what ID is supposed to go where under what circumstances - is a sufficiently large issue that I've been leaning towards adding additional issues for it but have been indecisive as to what they actually are. :D So I'ma continue to take some time to sketch that out and some new stuff may appear in this tracker later.

**Comment by Viqsi** [comment]
...or, put more succinctly, this is blocked by #33 :D

**Comment by WValenti** [comment]
Latest approach (now working) has reverted to a single resultSetId 1 '-- ALL Individuals --'.  It is, however, in tables that can be per-user, so a restricted set of '-- ALL Individuals --' is still possible for access control. Remapping is still available as well, but no longer used to point to '-- ALL Individuals --'.
