### ISSUE TITLE
Implement preview of PDF pages for reviewing variable context

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#12]

**Comment by Viqsi** [comment]
By "context" this means the PDFs pages from each interview, correct?

**Comment by Viqsi** [comment]
OK. Yeah. I think Digital Wave punted on how this stuff would be displayed; I don't know if we need/want to involve them or not.

The necessary information is not yet exposed in diverRPC, but I suppose it could be. I don't know if we've really settled on how to expose that; I'd have to look at how it's being handled in the prototype first.

**Comment by Viqsi** [comment]
General consensus is we'll probably just do this as "pop up another window" so as to not add to the Digital Wave contract.

**Comment by WValenti** [comment]
I looked into doing this for React and found this: https://www.geeksforgeeks.org/how-to-display-a-pdf-as-an-image-in-react-app-using-url/.  Not a high priority, but it looks like what we want because we can specify page and add [next] and [previous] page buttons to the display of the initial page.

**Comment by Viqsi** [comment]
How this is going to be presented has been reworked a tad thanks to the switch to Always FHVs. The presentational part is done, but we still need working links to PDFs. So that's one of the next things on my list.

**Comment by WValenti** [comment]
This was implemented in the prototype so the links and page offsets are
good.  We just need a local (to diverweb) store for the files!  Lemme know
where you want them.

**Comment by Viqsi** [comment]
The infrastructure is there; the PDFs themselves aren't in the repo. I don't have that many immediately to hand and am hesitating to put them in the repo due to size considerations anyways. They'd go in `public/codebooks/`.

**Comment by WValenti** [comment]
All codebooks are on diver.mathmed.org in /home/wvc/CODEBOOKS.

**Comment by Viqsi** [comment]
I've copied the ones the database actually references to `public/codebooks/` on both d.m.o and ada. So those links should now be live. Further issues would be separate bugs.
