### ISSUE TITLE
Need actual description text for pages (Never use "lorem ipsum" again!)

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#17]
It didn't occur to me while we were reviewing development, but having ALL TEXT be "lorem ipsum" makes it impossible for me to search the source archive for where I should make changes to text.  If the text said something like "dummy text for new cohort page", I could find the right source in a flash.

Nothing to do here but grieve.

**Comment by WValenti** [comment]
I've got it!  A script that traverses all source replacing any occurrence of "lorem ipsum" with the path, file and line range of the text.

**Comment by Viqsi** [comment]
Let's call that "Plan B". :)

**Comment by WValenti** [comment]
Sherri adds her vote to this one with her first item: "Would be helpful to outline/define what this tool does, which I would imagine would be added in the text areas available; E.g., what is a variable set vs. project vs. cohort?, how to do certain things."

**Comment by Viqsi** [comment]
Assigning to Public Beta becuase our internal beta testers are also the ones most likely to be involved in writing this text. :)
