### ISSUE TITLE
Constraint types differ between diverRPC and diverWeb and need to be reconciled

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#25]
Constraints are CONTAINS, DOES NOT CONTAIN, STARTS WITH and ENDS WITH, all of which could be regexes or use SQL's LIKE. Perhaps a control to allow selection of matching method would solve all at once?

**Comment by Viqsi** [comment]
For one, I must pro forma voice my objections to exposing SQL commands to the user. :)

As to the issue itself - those constraints were all done with  note the following comment in diverweb's src/utils/constraints/constraints.js:
```
/**
 * @todo
 * Some of these are assumed/have not been implemented on the API/BE yet
 * and therefore may need to be revisted
 */
```
So far as I can tell the idea was that they're all uses of REGEX, and REGEX itself hasn't been made directly available to the user. So we'd need to discuss in what form we want the full constraint list exposed.

**Comment by Viqsi** [comment]
For the record, diverRPC presently exposes the following:
EXISTS (variable is there)
VALID (variable has a valid answer)
EQ (exactly equal to)
NEQ (not equal to)
GT (greater than)
LT (less than)
REGEX (regular expression matching of value)
BETWEEN (between two values)
ANYOF (list of possible values)
UNION (set operation)
INTERSECT (set operation)
SUBTRACT (set operation)

diverWeb has the following (taken from constraints.js):
EXISTS
NEXISTS
VALID
ANYOF
CONTAINS
NCONTAINS
STARTS
ENDS
EQ
NEQ
GT
LT
BETWEEN
LISTANY
LISTALL
LISTNONE
(the set operations are presumably defined elsewhere)

Some of those are obviously 1:1 relationships. Others are... I dunno.

**Comment by Viqsi** [comment]
Further commentary on what diverWeb exports and its feasability with what we already have.

CONTAINS, NCONTAINS, STARTS, and ENDS are all (in the code, experimentally) based on REGEX. That can be "syntactic sugar" for the user. No problems there.

I confess I do not see the difference between ANYOF and LISTANY. Would want to chat about that with Digital Wave, definitely. (This also affects any comprehension of LISTALL and LISTNONE.)

I'm not sure how we would even *implement* NEXISTS. @WValenti - suggestions? Do we even want this?

**Comment by WValenti** [comment]
> I'm not sure how we would even _implement_ NEXISTS. @WValenti - suggestions? Do we even want this?

I can't think of any use.

**Comment by Viqsi** [comment]
After splitting out the LIST* stuff, all that's left for this issue is "REGEX needs to be exported, and NEXISTS shouldn't be". Those we can do at our leisure.

**Comment by WValenti** [comment]
API wants REGEX instead of RLIKE.  Changing enum in databases. Aaaand this required making REGEX known to the webapp.  Currently translating REGEX to contains, which is wack by me, but it keeps the webapp from crashing.

**Comment by Viqsi** [comment]
I did some preliminary trimming with MathematicalMedicine/diverweb@4e50030 so that this can be closed for now. The remaining concerns have to do with implementing of LIST type variables, which is a separate issue.
