### ISSUE TITLE
API REGEX constraint called incorrectly by webapp

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#38]
When invoking API_NewResultSet_REGEX from the webapp (CONTAINS?! constraint), the last parameter (the regular expression itself) comes through as /value/:

mysql (diver.mathmed.org DIVER)>Select * from Diag where DiagId = 344\G
*************************** 1. row ***************************
      DiagId: 344
ConnectionId: NULL
  InsertTime: 2022-06-01 20:44:30
     Message: API_NewResultSet_REGEX entry with: inUserName [testuser], inUserPrivs [__ALL__], inNewName [Have tissue (via REGEXP)], inNewDesc [''], inParentSet [1], inConstrainVariable [dist_cell_id], inHarmonyIncl [Y], inVariableREGEX [/value/i],

**Comment by Viqsi** [comment]
This appears to have already been fixed as of MathematicalMedicine/diverweb@0ee2ec6 so closing.
