### ISSUE TITLE
Still something wrong with JSON argument for ANYOF

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#40]
Call constraining dist_gwas_repo_code with [dbGaP, CAPS, NIMH] blew-up API with pymysql.err.OperationalError: (4038, "Syntax error in JSON text in argument 1 to function 'json_extract' at position 2")

2nd call with ["dbGaP", "CAPS", "NIMH"] just didn't get any results.

**Comment by Viqsi** [comment]
Calling this covered by #37 and closing.
