### ISSUE TITLE
Empty result to SP call from API for search doesn't clear display of previous results

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#47]
This started out as empty results incorrectly raises an error (raises DBDeniedError which doesn't seem to do anything), but changing invocation of proccall_errcheck to include "empty_OK" as True fixes that. Unfortunately if you've done earlier searches that DID return results, they remain listed even though the count of results correctly goes to zero.

**Comment by Viqsi** [comment]
(Affected by HG Supervariables because that involves significant changes to search)

**Comment by Viqsi** [comment]
Can no longer reproduce this bug after significant revisions to search due to FHV work. The error message is still a minor issue, but that's tracked in #48, so we're done here.
