### ISSUE TITLE
Implement variable sets

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#5]
Created two different ones to verify, nothing is saved, but then again, I don't recall implementing anything to save them yet. Hmm.

**Comment by Viqsi** [comment]
Code has been written for this but not yet fully verified. So it might already be done. Mostly. Will be reviewing Any Moment Now.

**Comment by WValenti** [comment]
It is done and being demo'd.

**Comment by Viqsi** [comment]
Not closing this one quite yet because it's not yet in the test suite and that needs to be acknowledged. Maybe that's a separate issue. Still working out how we're organizing this. But noting that initial implementation is done.
