### ISSUE TITLE
diverweb error popups should display API-returned error messages

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#56]

**Comment by WValenti** [comment]
Should have mentioned that I'm doing this if you try to delete projectId 1.

**Comment by Viqsi** [comment]
So I was at first thinking we had an interaction issue, but the nthere was some unexpected face-to-face discussion...

After that, it's clear that this at least gives an error message, so there's no serious interaction failure going on. The only concern is that the error message is a little generic. That puts it lower on the priority list IMO.

**Comment by WValenti** [comment]
Not to torpedo your interpretation, but it is possible that the error I got
was because the returned result set was unexpected.  So there can be an
interaction failure.

**Comment by Viqsi** [comment]
In the interests of sanity, productivity, and specificity, I'm not going to start presuming errors are worse than they appear until they actively demonstrate that they are.

**Comment by WValenti** [comment]
I have a simple example of how I might be doing error return from SPs wrong, because it doesn't display the text of the error now.  It is in API_CreateConstructVariable when it is called with an already-existing variable name (either construct or interview variable).  diverweb displays this:
![Screenshot 2022-12-15 at 9 23 17 AM](https://user-images.githubusercontent.com/3909236/207886147-265913aa-12f8-44c8-9ae8-f36949c3e8f9.png)
And the debug output from diverRPC.py is this:
![Screenshot 2022-12-15 at 9 23 39 AM](https://user-images.githubusercontent.com/3909236/207886257-1f2713da-7d00-4576-b9a8-2f7582d3171c.png)

**Comment by Viqsi** [comment]
That's not your fault. I have yet to see any case in which diverweb actually displays error messages the API sends it; it just says "nope, didn't work".

**Comment by WValenti** [comment]
Good question for Annalisa!
