### ISSUE TITLE
Deletion of a cohort leads to crash

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#7]
While viewing logic of a cohort, clicking (i) "Show description" and using the 'trash can' to delete the cohort and confirming with the cohort name seems to work, but the webapp crashes afterwards.

![Screen Shot 2022-03-01 at 1 36 12 PM](https://user-images.githubusercontent.com/3909236/156228553-e02f3218-4b81-4066-9794-f513e7cc3b83.png)

**Comment by Viqsi** [comment]
Having trouble reproducing this one all of a sudden...

**Comment by WValenti** [comment]
Does not occur with clean result set tables.
