### ISSUE TITLE
Value definitions not displayed after "Combine 2 Variables" construct creation

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#71]
construct variable AHxHearingImp was created fine and parses fine, but after creation the diverweb UI does not display the value definitions. Please see the two attached screenshots:

![Screen Shot 2022-11-11 at 4 43 59 PM](https://user-images.githubusercontent.com/3909236/201435251-a93690da-f881-4f57-bb0b-f489138227ee.png)
![Screen Shot 2022-11-11 at 4 43 50 PM](https://user-images.githubusercontent.com/3909236/201435252-871cd3cf-0920-4f1a-8c93-3f75ae2fb849.png)

**Comment by WValenti** [comment]
This screenshot is what value definition looked like during creation:
![Screen Shot 2022-11-11 at 4 20 23 PM](https://user-images.githubusercontent.com/3909236/201435367-d60be385-e427-4d49-bab3-23808d80a187.png)

**Comment by Viqsi** [comment]
Just noticed while working on #75 (it was also visible in the screenshots here but I overlooked it) that what might be going on is that the variable types are not being determined correctly. Note the discrepancy between possible answers "during creation" versus "at display time".

Fix that and I bet we fix the display.
