### ISSUE TITLE
Including a dist_ variable in Combine Two Variables loses a dimension of the values grid during creation

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#78]
Jo suggested this might be because of the dist_ variable, and that turns out to be true.  Apparently we're missing something that the variables we've typically been testing with have but dist_ ones don't.

**Comment by Viqsi** [comment]
My *presumption* is that what's missing is properly populated `possible_values` and `value_mapping` information for those variables, but I haven't actually checked.

**Comment by WValenti** [comment]
This is verified by me, but might be better solved in diverweb as opposed
to the database or SPs.  Suggestions solicited.

**Comment by Viqsi** [comment]
I genuinely cannot imagine what kind of "solved in diverweb" approach might actually be better. The information is in the database; should the database not provide it? diverweb would have to make a ton of round-trips to get that info, which would be rather slow and painful...

**Comment by WValenti** [comment]
There will always be situations in which the possible values and their
meanings might not be in the database (yet?), so I was thinking some kind
of behavior that gave the user a way to enter info without having values
and meanings automatically retrieved for them.

**Comment by Viqsi** [comment]
True for meanings and all possible values, but I'd have thought all *known and entered* values would be easily done on the backend. Obviously that wouldn't cover cases in which there are possible answers that were never used, but I suspect a user creating a construct is unlikely to care about such cases anyways.

**Comment by WValenti** [comment]
Fair enough. Assign it to me.

**Comment by WValenti** [comment]
Very few of the dist_ variables had the variable_response_interpretations table filled-in. That was the problem.
