### ISSUE TITLE
Prompting for 2nd cohort in set operations is damaged

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#99]
The first of two cohorts in a set operation is automatically selected because you pick the operation off the cohort entry. The second is not selectable because no cohorts show up at all when "All Cohorts" is chosen, and only "-- All Individuals --" shows up when "Favorite Cohorts" is chosen (and that's the default for some reason).

This is a particularly bad bug as it completely eliminates cohort-based construction, and cannot be bypassed.

![Screen Shot 2023-02-16 at 3 49 48 PM](https://user-images.githubusercontent.com/3909236/219483785-8339b6dd-770d-4ab5-a542-5f1e93e1c240.png)

**Comment by WValenti** [comment]
This appears to be because the webapp has the wrong project_id for the request. As can be seen from the attached screenshots, the project_id is 12, and the request is for 1.
![Screenshot 2023-02-16 at 4 19 12 PM](https://user-images.githubusercontent.com/3909236/219489528-8127a482-bd1a-46ff-bc59-197efba1cc19.png)
![Screenshot 2023-02-16 at 4 18 45 PM](https://user-images.githubusercontent.com/3909236/219489547-056e9c47-c06f-4faf-ad4e-359f03f6efdc.png)

**Comment by Viqsi** [comment]
This is *partially* fixed by the commit mentioned; we get the proper project ID now, and one can use "My Favorite Cohorts" to get a list of all of the cohorts in the current project (because of #107). The lack of working All Cohorts selection is being tracked as a separate issue (#106).
